fix to cause error when exit Omega Challenge
Reproduce:

1. Load the data which is in Omega Challenge.
2. Exit Omega Challenge.
3. Idle some durations.
4. Check to cause
  > function.js:186 Uncaught TypeError: game.iups[1].toNumber is not a function
  or
  > ExpantaNum.js:1297 Uncaught RangeError: Maximum call stack size exceeded